export { default as ComikamediaNavbar } from './ComikamediaNavbar'
export { default as Comikamedia } from './Comikamedia'
export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Search } from './Search'
export { default as Twitter } from './Twitter'
export { default as Youtube } from './Youtube'